# Generated by Django 5.2.2 on 2025-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
